version: "3"

services:
  node:
    build: .
    user: node
    container_name: ssbook
    tty: true
    stdin_open: true
    command: sh
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000